import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const GrotekMxRwnd = localFont({
  variable: "--font-grotek-mx-rwnd",
  src: [
    {
      path: '../fonts/GrotekMxRwnd-Hairline.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../fonts/GrotekMxRwnd-Thin.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../fonts/GrotekMxRwnd-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../fonts/GrotekMxRwnd-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/GrotekMxRwnd-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/GrotekMxRwnd-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../fonts/GrotekMxRwnd-Black.ttf',
      weight: '900',
      style: 'normal',
    }
  ],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GrotekMxRwnd.variable} h-full bg-black`}>
      <body className="h-full bg-black">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
